### ISSUE TITLE
Cojen is not compatible with JDK8

### ISSUE THREAD

**Issue by tcollignon** [cojen/Cojen#1]
Hello,

I try to use Cojen with JDK8, but I have this failure when I scan stream or lambda :

`
java.io.IOException: Invalid constant pool tag: 18
    at org.cojen.classfile.ConstantPool.readFrom(ConstantPool.java:376)
    at org.cojen.classfile.ClassFile.readFrom(ClassFile.java:159)
    at org.cojen.classfile.ClassFile.readFrom(ClassFile.java:136)
    at org.cojen.classfile.ClassFile.readFrom(ClassFile.java:112)
    at org.cojen.classfile.ClassFile.readFrom(ClassFile.java:70)
`

This is because it use invokeDynamic.

Do you think you can fix this ? Or can you give me some advice and I will try to make a PR.

Note : I have java.io.IOException: Invalid constant pool tag: 15 error too

Thank you

**Comment by broneill** [comment]
Cojen hasn't been updated to support Java 8, and there are no plans to do so. However, it should be possible to decompile Lamba features, or at least skip them with a few simple changes. Generation of these new features (as well as supporting anything past Java 5) requires many more changes to Cojen.

**Comment by tcollignon** [comment]
Thanks for your anwswer.

Yes I undertsand that let Cojen compatible with JDK 8 is a hard work.

Can you tell me How I scan skip JDK 8 feature please? 
=> I add value in ConstantInfo et what I must do in constantPool switch?

Thank you

**Comment by broneill** [comment]
Add these to ConstantInfo:

```
public static final int TAG_METHOD_HANDLE = 15;
public static final int TAG_METHOD_TYPE = 16;
public static final int TAG_METHOD_INVOKE_DYNAMIC = 18;
```

And add this to ConstantPool.readFrom, in the switch statement:

```
        case ConstantInfo.TAG_METHOD_HANDLE:
            din.skipBytes(3);
            constant = new ConstantUTFInfo("method_handle");
            break;

        case ConstantInfo.TAG_METHOD_TYPE:
            din.skipBytes(2);
            constant = new ConstantUTFInfo("method_type");
            break;

        case ConstantInfo.TAG_METHOD_INVOKE_DYNAMIC:
            din.skipBytes(4);
            constant = new ConstantNameAndTypeInfo
                (new ConstantUTFInfo("invoke_dynamic"), new ConstantUTFInfo("L_FIXME;"));
            break;
```

**Comment by broneill** [comment]
I pushed these changes to the master branch. Let me know if it works.

**Comment by tcollignon** [comment]
Oh it's very nice with this changes !
Thanks a lot, it works in my case

I'll be right back if I have others problem, but for now it's good

I think you can do a 2.2.6 release with that :)

Regards
