### ISSUE TITLE
I hope more detailed examples

### ISSUE THREAD

**Issue by isydl** [cojen/Cojen#2]
Hello!
I am very interested in your project.
but
Because my personal ability is not very good and my English is not good
I have a lot of problems when I use it.
Such as looping and judging
And the assembly order of the entire Java class
I hope you can get more detailed examples of your explanation.
(The source code has been read, but not much is understood)
thank you!

**Comment by broneill** [comment]
The Cojen project hasn't kept up with new Java versions, and so if you're new to Java byte code generation, you might want to use a different project. Someday I'd like to create a new, much easier to use version of Cojen, but I don't have the time.

**Comment by isydl** [comment]
Thank you for your answer.
I will continue to study it for the time being.
I hope that you can continue to create new and better works.
thank you.

**Comment by broneill** [comment]
The replacement: https://github.com/cojen/Maker
